### ISSUE TITLE
Meaning of number.of.digits in case of non-discreate numbers

### ISSUE THREAD

**Issue by hannes101** [carloscinelli/benford.analysis#13]
Hi Carlos,

thanks a lot for this package, it's really useful! I am asking about the meaning of this option, since I am not sure what exactly it means. I am analysing interest rate data and thus I am not sure what exactly it means, that in the documentation it states that "number.of.digits" defines how many first digits to analyse.
Does it care about the decimal separator of a numeric value or does it just take the number in as it is, like 035 for an interest rate of 0.35%?

Thanks a lot for some clarification

**Comment by carloscinelli** [comment]
Hi, hannes!

No, the decimal separator does not matter. So, for instance, 0.35 is for all purposes 35. Which means the first valid digit is 3 and the second valid digit  is 5. 

The number of digits argument tells to the function whether you want to analyze the pattern of only the first digits or the first and second digits together.
