### ISSUE TITLE
Add option to select certain digits and analyze them separately

### ISSUE THREAD

**Issue by hannes101** [carloscinelli/benford.analysis#14]
I would like to ask if it would be possible to add an option so as to make it possible to not only analyze subsequent digits together with the first digits, but alone. 
I know that this is not really in the spirit of the original benford analysis, but it would be interesting to check the distribution of the digits alone and it probably would be pretty easy to implement, or? I will try to come up with something on my own, so that it becomes a bit clearer, what I mean with this request.

All the best,
Johannes

**Comment by carloscinelli** [comment]
You mean only the distribution of the 2nd digits, or only the distribution of the 3rd digits and so on?

**Comment by hannes101** [comment]
Yes, exactly. I checked the code today and I think it's probably a bit more complicated than I thought ;-)

**Comment by carloscinelli** [comment]
It's not hard to do it, you can use the function `p.this.digit.at.n` to get the probability of the digit at that position. But I don't have time to implement this now. Also notice that the distribution quickly converges to a uniform after the second digit.

**Comment by hannes101** [comment]
Ok, will try to work on it. Perhaps I'll also try to provide patches, if it might be worthwile to add to your package.

**Comment by hannes101** [comment]
I just had the idea, that it's probably easier to just enter the relevant digit into the functions. So there's no need to alter the functions and one only needs to find a robust way to filter out the digit one would like to analyze.
