### ISSUE TITLE
Additional function to use MAD to assess conformity to Benford's Law

### ISSUE THREAD

**Issue by hannes101** [carloscinelli/benford.analysis#15]
Hi Carlos,

since I stumbled across the problem that the Chi-Square tests suffer from excess power, when using a lot of observations. I've implemented a rather simple function to implement the check based on the MAD as proposed by Nigrini (2012, Chapter 7, page 160).
I basically just check the MAD value based on the digits analyzed and then just print out the decision based on Nigrinis intervals. Don't know if that's a valuable contribution, but at least it's an additional point to add, since the Chi-Square test often leads to wrong conclusions.

Cheers,
Johannes
[201803_MAD_Conformity.txt](https://github.com/carloscinelli/benford.analysis/files/1825224/201803_MAD_Conformity.txt)
Nigrini, M.J. (2012). Benford's law. Applications for forensic accounting, auditing, and fraud detection (Hoboken, NJ: Wiley).

**Comment by carloscinelli** [comment]
Thanks, Johannes, will take a look! 

If you also want to try to implement it and make a pull request, feel free to do it!

**Comment by hannes101** [comment]
First time for a pull-request, so sorry in advance for breaking anything ;-)
I didn't want to mess around in too many places, but it probably could be added to the benford.analysis printout, but this would require some more work and I don't know if you would like that or not, so I didn't work on it anymore.

**Comment by carloscinelli** [comment]
Hi Johannes, I included a MAD conformity function, and it now prints the MAD conformity by default (GitHub version), thanks!
