### ISSUE TITLE
Planning paper on Benford Analysis using your package

### ISSUE THREAD

**Issue by kieroneil** [carloscinelli/benford.analysis#17]
Carlos,  are you still maintaining this package?  I saw that there was an update in 2017 but not much activity otherwise.  
I recently was asked to perform a Benford Analysis in my professional work on financial data and your package was very helpful.  I am going to write a general paper that might be turned into a vignette and would like to reach out to you if I have specific questions.  
Thanks for building this.
Kier

**Comment by carloscinelli** [comment]
Hi Kier, yes, I'm still maintaining the package, although not actively developing new functionality, since other papers and projects have priority. Feel free to reach out or give suggestions!

> Carlos, are you still maintaining this package? I saw that there was an update in 2017 but not much activity otherwise.
> I recently was asked to perform a Benford Analysis in my professional work on financial data and your package was very helpful. I am going to write a general paper that might be turned into a vignette and would like to reach out to you if I have specific questions.
> Thanks for building this.
> Kier

**Comment by kieroneil** [comment]
Carlos,  
Is this the best place to reach out to you or is it better to communicate through email. If you prefer email just send me a note to koneil@kpmg.com and I'll use the email address that you sent from.  
My first question is how to interpret the middle two charts from the plot function.  I'm not sure how to explain it to people.  
Thanks.
