### ISSUE TITLE
Adjustment in plot functions 

### ISSUE THREAD

**Issue by carloscinelli** [carloscinelli/benford.analysis#25]
@rafaelslins 

- [x] the argument grid=F is not working for the summation graph

- [x] remove rootogram from the default plots, 8 plots as default is too much.

- [x] Change title: "Barchart of digits" --> "Digits distribution\nBarchart". Where "\n" is a line break.

- [x] Change title: "Rootogram of digits" --? "Digits distribution\nRootogram".

- [x] Do the same for sencond order but now "Digits distribution\nSecond Order Test - Barchart", "Digits distribution\nSecond Order Test - Rootogram".

- [x] Can we remove the extra white-space in the Chi-squared and summation difference plots?

**Comment by rafaelslins** [comment]
Hi Carlos,

There is a limitation on the number of characters to use according to this message:

"  Rd file 'plot.Benford.Rd':
    \usage lines wider than 90 characters:
       plot(x,except=c("mantissa","abs diff","rootogram digits","rootogram second order"),multiple=TRUE,col.bar="lightblue",grid=TRUE, ...)
  
  These lines will be truncated in the PDF manual.

0 errors v | 0 warnings v | 1 note x"

It seems not possible to remove rootograms by default. What to do not to break the code?

**Comment by carloscinelli** [comment]
Remove the usage section, Roxygen will create the correct break by default.

**Comment by rafaelslins** [comment]
Done!
