### ISSUE TITLE
Warning messages in simple example

### ISSUE THREAD

**Issue by carloscinelli** [carloscinelli/benford.analysis#42]
This example creates warning messages:

test <- benford(1000)

Verify what is going on.

**Comment by rafaelslins** [comment]
Carlos,
It seems like just a record makes it unrealizable to take the second order test (if N = 1 so there's 0 difserences). Some lines of the code related to calculating the second order distribution don't work well. The error source starts when extract.digits function returns "NA". I think that in this case the function to calculate the second order distribution could not be called

**Comment by carloscinelli** [comment]
@rafaelslins got it. Since it doesn't make sense to analyze one observation only, we should check the data set size and if the size is one return an informative error message "data comprised of only one observation, no meaningful analysis is possible."

**Comment by carloscinelli** [comment]
This can be done in the refactor branch as well
