### ISSUE TITLE
usage of 'select' and 'except' arguments

### ISSUE THREAD

**Issue by rafaelslins** [carloscinelli/benford.analysis#48]
data(corporate.payment)
cp <- corporate.payment$Amount
plot(cp, select = "digits", except = "digits")
plot(cp, select = "none", except = "all")

**Comment by carloscinelli** [comment]
- select should override except. Whenever both are provided, there should be a warning message saying that except will be ignored.
- select = "none" should not be an option
- except = "all" should not be an option

**Comment by carloscinelli** [comment]
Yes, it is simpler to have an argument that overrides the other. In this case, select. The behavior should be documented and also there should be a warning explaining the behavior.
